name: coverage badge in local

on:
  push:
    branches: [main]

jobs:
  checks:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Install modules
        run: yarn --prefer-offline

      - name: Run unit tests with coverage
        run: |
          touch fluir_coverage.json
          SUMMARY="$(yarn jest --coverage --coverageReporters=text-summary | tail -3 | head -1)"
          TOKENS=($SUMMARY)
          echo "COVERAGE=$(echo ${TOKENS[2]})" >> $GITHUB_ENV
          echo '{"schemaVersion":1,"label":"coverage","message":"$(echo ${TOKENS[2]})","color":"blue","namedLogo":"jest","logoColor":"lighblue"}' >> ./fluir_coverage.json
          echo "ls -a ${{ github.workspace }}"
          ls -a ${{ github.workspace }}
          echo "cat fluir_coverage.json"
          cat fluir_coverage.json
